name = "ppc-homebase"
main = "src/index.js"
compatibility_date = "2026-07-02"

kv_namespaces = [
  { binding = "PLANNER_KV", id = "2f3dc18365c2477595cc76e4f3303746" }
]

[assets]
directory = "./public"
